#!/usr/bin/env python

import sys
from PyQt4 import QtGui, QtCore
from Jixi.connectionPanel import connectionPanel
from Jixi.statusPanel import statusPanel
from Jixi.commandPanel import commandPanel
from Jixi.consolePanel import consolePanel
from Jixi.jSerialThread import jRead
from Jixi.jConfig import jConfig
from Jixi.jComPort import jComPort
import Jixi.jStatus
import serial

class jixiApp(QtGui.QApplication):

  def __init__(self, args):
    super(jixiApp, self).__init__(args)
    self.config = jConfig()
    self.comport = jComPort()
    self.readThread = jRead(self.comport)



class mainWindow(QtGui.QMainWindow):


    def __init__(self):
        super(mainWindow, self).__init__()
        self.setWindowIcon(QtGui.QIcon('web.png'))
        self.statusBar().showMessage('Ready')
        c = QtGui.QWidget()
        self.setCentralWidget(c)

        # grid to hold all panels
        grid = QtGui.QGridLayout()
        c.setLayout(grid)

        # connection panel
        self.connectionw = connectionPanel()
        grid.addWidget(self.connectionw, 0,0)

        # status panel
        self.statusw = statusPanel()
        grid.addWidget(self.statusw, 1,0)

        # command panel 
        self.commandPanelw = commandPanel()
        self.commandPanelw.serial_send_signal.connect(self.serial_write)
        grid.addWidget(self.commandPanelw, 0,1, 2, 1)

        # console panel
        grid.addWidget(consolePanel(), 2,0, 1, 2)

        self.comport = QtCore.QCoreApplication.instance().comport
        self.readThread = QtCore.QCoreApplication.instance().readThread
        self.comport.connected.connect(self.connected)
        self.comport.open()
        self.readThread.read_signal.connect(self.read_data)
        self.readThread.start()

        self.show()

    # process a line of data from the serial port
    def read_data(self, txt):
        txt = str(txt).strip()
        Jixi.jStatus.msg(txt)
        if (txt[0]=='<' and txt[-1]=='>'):
            # looks like a status message
            self.statusw.update(txt)

    # display connection status
    def connected(self, isconnected):
        self.connectionw.show_connected(isconnected)

    # send data to the serial port
    def serial_write(self, txt):
        self.comport.write(str(txt))


app = jixiApp(sys.argv)
w = mainWindow()
sys.exit(app.exec_())


