#!/usr/bin/env python

import sys
from PyQt4 import QtGui, QtCore
from Jixi.connectionPanel import connectionPanel
from Jixi.statusPanel import statusPanel
from Jixi.commandPanel import commandPanel
from Jixi.consolePanel import consolePanel
from Jixi.jSerialThread import jSerialThread

class mainWindow(QtGui.QMainWindow):

    def __init__(self):
        super(mainWindow, self).__init__()
        self.setWindowIcon(QtGui.QIcon('web.png'))
        self.statusBar().showMessage('Ready')
        c = QtGui.QWidget()
        self.setCentralWidget(c)

        grid = QtGui.QGridLayout()
        c.setLayout(grid)

        grid.addWidget(connectionPanel(), 0,0)
        grid.addWidget(statusPanel(), 1,0)
        grid.addWidget(commandPanel(), 0,1, 2, 1)
        grid.addWidget(consolePanel(), 2,0, 1, 2)

        self.jSerial = jSerialThread()
        self.jSerial.start()

        self.show()

app = QtGui.QApplication(sys.argv)
w = mainWindow()
sys.exit(app.exec_())


